api:
  listen: 8085
cors:
  origins:
    - http://127.0.0.1:3000
    - http://127.0.0.1:8085
    - http://localhost:3000
jwt:
  email: 1982209
  key: Wsr1
smtp:
  host: smtp.qq.com
  password: dlbeaal
  port: 465
  username: 1982209
routes:
  - /reset
  - /add
  - /home
  - /
